### ISSUE TITLE
process being used or Bad response from Docker engine error

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/cattle#1]
Hi, I'm not sure about the sequence of commands I need to actually run this:

I've tried to get this up and running:

```
git clone https://github.com/albertmeronyo/cattle.git
# docker-compose build #not sure I actually need this
docker-compose up
```

which results in:

```
Starting cattle_cattle_1 ...
Starting cattle_cattle_1 ... error

ERROR: for cattle_cattle_1  Cannot start service cattle: driver failed programming external connectivity on endpoint cattle_cattle_1 (5b53eee17e033a74e09c51d0de11ad1760c97c7daadcadbc153ea2fb7ec49e59): Bind for 0.0.0.0:8001 failed: port is already allocated
```

If I kill the specific process and retry it, I get:
`ERROR: Bad response from Docker engine`

The log of `docker-compose build` gives me two warnings:
```
Adding new user `cattle' (1000) with group `cattle' ...
adduser: Warning: The home directory `/home/cattle' does not belong to the user you are currently creating.

```
and

`/etc/docker-cattle/build/install.sh: line 56: warning: here-document at line 33 delimited by end-of-file (wanted `EOF')`

Hope this helps!

**Comment by albertmeronyo** [comment]
Hi @rlzijdeman , it seems you're already using port 8001 in your machine. You can try to shut down whatever service is using it (try to see if http://localhost:8001/ opens something in your browser), or alternatively change cattle's container default port to something else (by editing [this line](https://github.com/albertmeronyo/cattle/blob/master/docker-compose.yml#L8) in `docker-compose.yml`).

**Comment by rlzijdeman** [comment]
Hi @albertmeronyo , thanks! As noted above, I did try and kill the process, but the error remains. Changing the port (I used http://localhost:8035/) results in the following error: 

`ERROR: readlink /var/lib/docker/overlay2: invalid argument`

**Comment by albertmeronyo** [comment]
Hi @rlzijdeman , I set a public instance at http://cattle.datalegend.net/
(the very purpose of having a docker container was to avoid config overhead! :) )
Let me know if that one works (I'll change the example requests in `README.md`
