### ISSUE TITLE
Gateway Timeout error still persists

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/cattle#11]
Unfortunately, the same Timeout error persists and the connection times out exactly at 60 seconds.
Tried converting the same (big) file on Internet Explorer and Chrome (Windows 10, my laptop) and Firefox (Windows 7, standard IISG desktop).

**Comment by Bramvdhout** [comment]
Trying to convert the same file with COW leads to the following error, maybe this is relevant?
![image](https://user-images.githubusercontent.com/32885158/34259143-5fdb5e80-e661-11e7-80c8-3b2077703a42.png)

During converting, the following is printed a few hundred times:
`DEBUG:converter.csvw:Traceback (most recent call last):
  File "C:\Datalegend\Clone\COW\cow\converter\csvw.py", line 440, in process
    elif len(value) == 0 or value == unicode(c.csvw_null) or value in [unicode(n) for n in c.csvw_null] or value == unicode(self.schema.csvw_null):
TypeError: 'NoneType' object is not iterable`

**Comment by Bramvdhout** [comment]
Experimented with number of rows and columns.
Normal file consists of 3222 rows and 9 columns.

**Removing rows**
The max number of rows before timeout is 3059. 3060 or more rows cause a timeout. Tried converting rows 3060 until 3222 to see if it had anything to do with the cells and their contents, but that conversion succeeded.

**Removing column**
Removed the last column (Column I) but no rows, for a total of 3222 rows and 8 columns. Conversion successful.

**Hypothesis**
Max number of cells for Cattle could be _around_ `3059 * 9 = 27531`. Needs more testing with other large CSV files.
Shortened CSV file still results in the error mentioned in the above comment.

**Comment by albertmeronyo** [comment]
Hi, I just increased the timeout, but the issue might be related to something else that we need to get thorugh the frontend (related to #7 ).
Worth a try though :)

**Comment by Bramvdhout** [comment]
Just wanted to let you know I tried it a few times, but still no luck. But there's no rush, I'll focus on other things first

**Comment by rlzijdeman** [comment]
This is fixed too: currently a link is given, that one copy and visit when the file is done. Could be still made a bit more user friendly though.
