### ISSUE TITLE
Upload button hard to click

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/cattle#13]
During the COW workshop, I noticed a few users having difficulty clicking the second Upload button at the button of the page, because the floating text 

> Adapted from cover template for Bootstrap, by @mdo.

was covering it, making it impossible to click. Was primarily a problem with users who had smaller screens (13") and used Safari. Might be (easily) solved by making the above text fixed at the bottom of the page instead of floating?

**Comment by mmmenno** [comment]
Had the same experience in chrome. Fixed position of footer seems to be the problem.
