### ISSUE TITLE
Difference NQ output between COW and Cattle 

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/cattle#17]
Ran into an interesting problem today.

When I convert with Cattle, the output contains /vocab/, like so:
`<http://data.socialhistory.org/resource/opgaaf/18> <https://iisg.amsterdam/vocab/khoemen> "0"^^<http://www.w3.org/2001/XMLSchema#integer> <https://iisg.amsterdamfgvf15oct_kort/assertion/25e84a6a/2018-07-12T09:41> .`

I don't know where `https://iisg.amsterdam/vocab/` comes from because it shouldn't be there according to the metadata.json

When I convert with COW, I get a correct ouput
`<http://data.socialhistory.org/resource/opgaaf/18> <http://data.socialhistory.org/resource/khoemen> "0"^^<http://www.w3.org/2001/XMLSchema#integer> <https://iisg.amsterdam/OpgaafTest2/assertion/25e84a6a/2018-07-12T10:07> .`

So somewhere Cattle is automatically applying `<https://iisg.amsterdam/vocab/`

**Comment by rlzijdeman** [comment]
NB: also, note that cattle messes up the last part of the quad:` iisg.amsterdamfgd` ... there should at least be a slash after `iisg.amsterdam`.

@RoderickvanderWeerdt could it be that cattle uses an old version of CoW?

**Comment by RoderickvanderWeerdt** [comment]
I don't think it uses an older version, because it downloads the most recent version of COW whenever it is build, and the latest build of CATTLE is younger then the latest version of COW. But I have a meeting with Albert later today and we'll discuss it.

**Comment by albertmeronyo** [comment]
I've looked into it and cattle uses the latest version of cow (0.30).
@Bramvdhout @rlzijdeman could you let us know what version of cow you're using ($ cow_tool --version) and attach your csv and json files?

**Comment by Bramvdhout** [comment]
I can't figure out how to find the version (`cow_tool --version` doesn't work/I don't know where to write in Terminal).

I quickly made a new conversion without modifying the JSON. `<https://iisg.amsterdam/vocab/Inhoud>` and `<https://iisg.amsterdamANRI/assertion/b21b26f8/2018-08-02T11:48>` show the same problems.

Sending files over Slack.

**Comment by rlzijdeman** [comment]
confirming @Bramvdhout 's `cow_tool --version` report: on my comp it says: 
```
(COW) xxx:src xxx$ cow_tool --version
usage: cow_tool [-h] [--dataset DATASET] [--delimiter DELIMITER]
                [--quotechar QUOTECHAR] [--processes PROCESSES]
                [--chunksize CHUNKSIZE] [--base BASE]
                {convert,build} file [file ...]
cow_tool: error: too few arguments
```

**Comment by RoderickvanderWeerdt** [comment]
Two different versions of COW exist in the cow folder (https://github.com/CLARIAH/COW/issues/60).
I believe this causes the problem of the different outputs, since some fixes have been performed to one version, and some to the other. I will go through both of the COW folders to see what the differences are, and which one is the best to keep using (and update with the changes from the other implementation).

**Comment by RoderickvanderWeerdt** [comment]
COW has been updated, and dev.cattle is using it, so when you update your COW version now, either by using pip to update or by pulling the git folder, it should give the same result as the dev version of Cattle does.
