### ISSUE TITLE
Link to provide feedback on error

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/cattle#19]
It would be great that the error pages show a mechanism to provide feedback (a simple mailto: will do).

Yesterday I was using a bit of software and when it broke, I got a popup where I could enter bug report info. Would it be feasible to have that in cattle? Maybe just as a <a href:mailto:> saying something like: “we’re sorry the cows are moohing at you. Please send a <mail> and tell us where we can help out. ” as part of each error message.

**Comment by Bramvdhout** [comment]
Agreed. For the low amount of traffic we currently have, this would improve the pipeline and user-friendliness massively. And it's a simple implementation.

**Comment by RoderickvanderWeerdt** [comment]
Does a Cattle (or datalegend) email account already exist?, or do we want to create a new email account for Cattle on gmail (or something similar)?

**Comment by Bramvdhout** [comment]
We could link it to a Slack-bot, so we get a feed and not have to worry about checking it all the time

**Comment by RoderickvanderWeerdt** [comment]
For the first version I used the simple mailto suggestion from Albert. At the moment it is running at dev.cattle and looks like this:

![schermafbeelding 2018-10-11 om 15 13 58](https://user-images.githubusercontent.com/14040777/46806623-5a4ba580-cd68-11e8-8673-bb3266381b6f.png)

The mailto for now directs to Richard (as was discussed with him).

I will look into a second version using a Slack-bot, but will this suffice for now?

**Comment by rlzijdeman** [comment]
awesome! idea this morning, done today. Kudos @RoderickvanderWeerdt 
ps: I will hunt for an institutional mail address for these and other data issues
