### ISSUE TITLE
how do I download the meta-data.json file?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/cattle#21]
Hi, I can't seem to download the json file after conversion?

**Comment by RoderickvanderWeerdt** [comment]
At the moment you can't download the json file at any point in the cattle progression. Would the ruminator page be a good place for a download (json) button? (or would that be too hidden?)

**Comment by Bramvdhout** [comment]
I vote right after building from CSV, Ruminator might be too hidden.

**Comment by rlzijdeman** [comment]
I second that.

On 23 Jul 2019, at 07:56, Bramvdhout <notifications@github.com<mailto:notifications@github.com>> wrote:


I vote right after building from CSV, Ruminator might be too hidden.

**Comment by RoderickvanderWeerdt** [comment]
So something like this?

![Schermafbeelding 2019-07-23 om 14 37 58](https://user-images.githubusercontent.com/14040777/61722763-28418800-ad6b-11e9-9c9e-7de9ccad0af3.png)

**Comment by rlzijdeman** [comment]
Yes like that. I’d say download json or Ruminate

On 23 Jul 2019, at 10:59, RoderickvanderWeerdt <notifications@github.com<mailto:notifications@github.com>> wrote:


So something like this?

[Schermafbeelding 2019-07-23 om 14 37 58]<https://user-images.githubusercontent.com/14040777/61722763-28418800-ad6b-11e9-9c9e-7de9ccad0af3.png>

**Comment by rlzijdeman** [comment]
This is solved. In the current version click 'Old School upload' and you can directly upload both the csv and metadata-json file.
