### ISSUE TITLE
cattle doesn't eat .tsv... unless you fake it!

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/cattle#22]
Hi,

some people tend to save tab separated files as .tsv . Cattle seems to hick-up on .tsv though... but if you save the file as .csv it works perfectly... perhaps also allow for *.tsv (it doesn't even seem necessary to force 'sep = \t'

**Comment by RoderickvanderWeerdt** [comment]
Cattle now eats tsv-files! internally cattle will rename all received tsv-files as csv-files, because as you found out COW can recognize the \t seperator by itself.

For now it is implemented only on dev.cattle, but it will work on cattle soon.

**Comment by rlzijdeman** [comment]
Hi @RoderickvanderWeerdt, it appears this solution doesn't appear to be working in daily practice. (the json is built, but it won't 'convert', even not when adapted)
I guess the reason is that people use .tsv to avoid issues with:
- having a list as cell value (separated by ';')
- a special instance of this: having comma delimited polygon features (i.e. a list of coordinates)
Would it be possible to do it with an if else clause?
'if .tsv 'convert to .csv'
' else (assuming that's .csv)-> great CoW/Cattle it'

The 'convert to .csv' I now do it manually via Python Pandas like this:
```
import pandas as pd
myext = ".tsv"
myfile = "ne_mountains_60"
mypath = "Xxx/git/whgazetteer/example_data/"
df = pd.read_csv(mypath+myfile+myext, sep = "\t")
df.to_csv(mypath+myfile+'.csv', index = False)
```

**Comment by RoderickvanderWeerdt** [comment]
You are right, the problem was that I already do this check within COW. So after the file was uploaded it was renamed "file.**csv**" but the separately uploaded json scheme was still named "file.**tsv**-metadata.json", so COW didn't recognize those two as belonging together.
I will add some code to make sure that the json file is also renamed.
