### ISSUE TITLE
upload size limit

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/cattle#25]
Hi,

I thought we had no more upload size limits, as the conversion would be handled in the background?
<img width="836" alt="Screenshot 2019-11-11 08 12 07" src="https://user-images.githubusercontent.com/3480446/68568238-5a324380-045b-11ea-910d-83e0b0722d00.png">

Best,

Richard

**Comment by rijpma** [comment]
I think this currently only works in the dev version. I'll send you a message

**Comment by rlzijdeman** [comment]
@RoderickvanderWeerdt has pushed the dev version to production, fixing the file size issue.
