### ISSUE TITLE
specify metadata file by command line option

### ISSUE THREAD

**Issue by bblfish** [CLARIAH/cattle#29]
I would like to specify the metadata file via the command line so that I can use the same metadata file for different csv files that implement the same schema. Using [Swirrl/csv2rdf](https://github.com/Swirrl/csv2rdf/) I can do something like this 

```sh
$ csv2rdf -t 20220204.csv -u 20220204.csv-metadata.json -m minimal > out.ttl
```

**Comment by rlzijdeman** [comment]
Hi! Thanks for leaving feedback! It no longer proved viable to develop both the server version of CoW (CATTLE) and CoW itself. So I've ported your issue to CoW. See: https://github.com/CLARIAH/COW/issues/145
