### ISSUE TITLE
image on website not showing

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/cattle#5]
Hi Albert,

I've added the cow-left.png logo to the cattle.datalegend.net website. Like you said it's not showing the image. I removed a trailing slash and hope to resolves the issues. Could you please update the server? (NB: locally it appears to be working... (but even with the trailing slash))

**Comment by albertmeronyo** [comment]
Fixed in 70131b9810c2c733f310567859ec5c7e1b6311eb

Thanks!
